export const CURSOR = {
  Normal: "default",
  Move: "move",
  In: "zoom-in",
  Out: "zoom-out"
  // auto: "auto",
  // none: "none",
  // context: "context-menu",
  // help: "help",
  // pointer: "pointer",
  // progress: "progress",
  // wait: "wait",
  // cell: "cell",
  // crosshair: "crosshair",
  // text: "text",
  // vertical: "vertical-text",
  // alias: "alias",
  // copy: "copy",
  // no: "no-drop",
  // not: "not-allowed",
  // e: "e-resize",
  // n: "n-resize",
  // ne: "ne-resize",
  // nw: "nw-resize",
  // s: "s-resize",
  // se: "se-resize",
  // sw: "sw-resize",
  // w: "w-resize",
  // ns: "ns-resize",
  // ew: "ew-resize",
  // nesw: "nesw-resize",
  // col: "col-resize",
  // nwse: "nwse-resize",
  // row: "row-resize",
  // all: "all-scroll",

  // grab: "grab",
  // grabbing: "grabbing"
}
